from app.adapters.schemas import NormalizedPrediction
from app.models import Evidence


def explain(prediction: NormalizedPrediction, extraction_notes: list[str]) -> tuple[str, list[Evidence], list[str]]:
    evidence = [
        Evidence(signal=signal, description=signal, severity="low", source=prediction.model_name)
        for signal in prediction.signals
    ]
    limitations = [
        "This result is generated by a development placeholder and is not genuine ML inference.",
        "A placeholder cannot establish provenance, intent, authorship, or factual truth.",
    ] + extraction_notes
    return "Insufficient evidence for a reliable authenticity determination.", evidence, limitations
