from app.adapters.schemas import NormalizedPrediction
from app.models import Evidence


def explain(prediction: NormalizedPrediction, extraction_notes: list[str]) -> tuple[str, list[Evidence], list[str]]:
    if prediction.model_name == "UnivFD-CLIP-ViT-L/14":
        evidence: list[Evidence] = []
        metadata = prediction.metadata
        numeric_details = (
            ("Raw logit", "raw_logit"),
            ("Sigmoid detector score", "sigmoid_score"),
            ("Inference duration (seconds)", "inference_duration_seconds"),
        )
        for title, key in numeric_details:
            value = metadata.get(key)
            if isinstance(value, (int, float)) and not isinstance(value, bool):
                evidence.append(
                    Evidence(
                        signal=title,
                        description=f"{title}: {value:.8g}",
                        severity="low",
                        source=prediction.model_name,
                    )
                )
        device = metadata.get("device")
        if isinstance(device, str) and device:
            evidence.append(
                Evidence(
                    signal="Inference device",
                    description=f"Inference device: {device}",
                    severity="low",
                    source=prediction.model_name,
                )
            )
        limitations = [
            "UnivFD is a binary fake/generated detector, not a validated three-class classifier.",
            "Its sigmoid output is not a calibrated probability and does not distinguish manipulation from synthesis.",
        ]
        return "Binary detector signal only; three-class classification is not established.", evidence, limitations
    evidence = [
        Evidence(signal=signal, description=signal, severity="low", source=prediction.model_name)
        for signal in prediction.signals
    ]
    if prediction.model_name == "experimental-text-baseline":
        limitations = [
            "Experimental text baseline only confirms receipt and length; it does not detect AI-generated text.",
        ]
        return "Experimental text baseline; no reliable authenticity determination is available.", evidence, limitations
    limitations = [
        "This result is generated by a development placeholder and is not genuine ML inference.",
        "A placeholder cannot establish provenance, intent, authorship, or factual truth.",
    ] + extraction_notes
    return "Insufficient evidence for a reliable authenticity determination.", evidence, limitations
