import { useEffect, useState } from 'react'
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, ArrowRight, BarChart3, CircleHelp, FileCheck2, History as HistoryIcon, Home, LogOut, Menu, Moon, MoreHorizontal, Settings as SettingsIcon, ShieldCheck, Sparkles, Sun, UploadCloud, UserRound, X } from 'lucide-react'
import { AuthProvider, useAuth } from './auth'
import { config } from './lib/config'
import { createAnalysis, getAnalysis, listAnalyses, transcribeAudio } from './lib/api'
import type { Analysis, Verdict } from './types'

const nav = [{ to: '/', label: 'Overview', icon: Home }, { to: '/analyze', label: 'Analyze content', icon: UploadCloud }, { to: '/history', label: 'Analysis history', icon: HistoryIcon }, { to: '/settings', label: 'Settings', icon: SettingsIcon }]
const verdictLabel: Record<Verdict, string> = { authentic: 'Likely authentic', manipulated: 'Likely manipulated', synthetic: 'Likely synthetic', uncertain: 'Needs review' }

export default function App() {
  return <AuthProvider><Routes><Route path="/login" element={<Login />} /><Route path="/help" element={<Help />} /><Route path="/*" element={<ProtectedShell />} /></Routes></AuthProvider>
}

function ProtectedShell() {
  const { session, loading } = useAuth()
  if (loading) return <div className="loading-screen"><ShieldCheck size={28} /><span>Loading SATYA...</span></div>
  if (!session) return <Navigate to="/login" replace />
  return <div className="app-shell"><Sidebar /><main className="main"><Topbar /><Routes><Route path="/" element={<Dashboard />} /><Route path="/analyze" element={<Analyze />} /><Route path="/results/:id" element={<Result />} /><Route path="/history" element={<History />} /><Route path="/settings" element={<Settings />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></main></div>
}

function Sidebar() {
  const location = useLocation(); const { session, signOut } = useAuth(); const navigate = useNavigate()
  const email = session?.user.email || 'Signed-in user'
  return <aside className="sidebar"><Link to="/" className="brand"><span className="brand-mark"><ShieldCheck size={19} /></span><span>SATYA</span></Link><Link to="/settings" className="workspace"><span className="workspace-dot" /><div><strong>Personal workspace</strong><small>{email}</small></div><ArrowRight size={15} /></Link><nav>{nav.map(({ to, label, icon: Icon }) => <Link key={to} to={to} className={location.pathname === to ? 'active' : ''}><Icon size={18} />{label}</Link>)}</nav><div className="sidebar-bottom"><Link to="/help"><CircleHelp size={17} />Help & docs</Link><button className="signout" onClick={() => void signOut().then(() => navigate('/login')).catch((error) => window.alert(error.message))}><LogOut size={17} />Sign out</button><Link to="/settings" className="profile"><div className="avatar"><UserRound size={14} /></div><div><strong>{email}</strong><small>Account settings</small></div><MoreHorizontal size={17} /></Link></div></aside>
}

function Topbar() {
  const location = useLocation(); const [dark, setDark] = useState(() => localStorage.getItem('satya-theme') === 'dark')
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem('satya-theme', dark ? 'dark' : 'light') }, [dark])
  const title = nav.find((item) => item.to === location.pathname)?.label || 'Analysis result'
  return <header className="topbar"><button className="mobile-menu" aria-label="Open menu"><Menu size={21} /></button><div><span className="eyebrow">Workspace / {title}</span><h1>{title}</h1></div><div className="top-actions"><button className="icon-button" aria-label="Toggle theme" onClick={() => setDark((value) => !value)}>{dark ? <Sun size={18} /> : <Moon size={18} />}</button></div></header>
}

function Dashboard() {
  const [items, setItems] = useState<Analysis[]>([]); const [error, setError] = useState('')
  useEffect(() => { listAnalyses().then(setItems).catch((err) => setError(err.message)) }, [])
  return <div className="page"><div className="welcome-row"><div><p className="kicker">Your workspace</p><h2>Welcome to SATYA <span>✦</span></h2><p className="muted">Make confident decisions about the content you encounter.</p></div><Link className="button primary" to="/analyze"><UploadCloud size={17} />New analysis</Link></div>{error && <p className="error">{error}</p>}<section className="stat-grid"><Stat icon={FileCheck2} label="Total analyses" value={String(items.length)} note="Saved in your workspace" /><Stat icon={BarChart3} label="Completed analyses" value={String(items.filter((item) => item.status === 'complete').length)} note="Based on available results" /><Stat icon={Sparkles} label="Latest result" value={items[0] ? verdictLabel[items[0].verdict] : 'None yet'} note={items[0] ? items[0].filename : 'Start an analysis to see it here'} /></section><section className="card recent-card"><div className="card-heading"><div><span className="section-label">Latest work</span><h3>Recent analyses</h3></div><Link to="/history" className="text-link">View history <ArrowRight size={15} /></Link></div><AnalysisTable items={items.slice(0, 4)} /></section></div>
}
function Stat({ icon: Icon, label, value, note }: { icon: typeof FileCheck2; label: string; value: string; note: string }) { return <div className="stat card"><div className="stat-icon"><Icon size={19} /></div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div> }

function Analyze() {
  const navigate = useNavigate(); const [file, setFile] = useState<File | null>(null); const [context, setContext] = useState(''); const [transcript, setTranscript] = useState(''); const [busy, setBusy] = useState(false); const [transcribing, setTranscribing] = useState(false); const [error, setError] = useState('')
  async function submit() { if (!file) return; setBusy(true); setError(''); try { const result = await createAnalysis(file, `${context}\n${transcript}`); navigate(`/results/${result.id}`, { state: { result } }) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to start analysis') } finally { setBusy(false) } }
  async function transcribe() { if (!file) return; setTranscribing(true); setError(''); try { setTranscript(await transcribeAudio(file)) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to transcribe audio') } finally { setTranscribing(false) } }
  return <div className="page narrow"><div className="page-intro"><p className="kicker">New assessment</p><h2>Analyze content</h2><p className="muted">Upload a file and give SATYA the context it needs to reason clearly.</p></div><div className="card upload-card"><div className="dropzone"><input id="file-input" type="file" accept="image/*,video/*,audio/*,.pdf,.txt,.doc,.docx" onChange={(event) => setFile(event.target.files?.[0] || null)} />{file ? <><div className="file-icon"><FileCheck2 size={25} /></div><strong>{file.name}</strong><span>{(file.size / 1024 / 1024).toFixed(2)} MB - Ready to analyze</span><button className="remove-file" onClick={() => { setFile(null); setTranscript('') }}><X size={14} /> Remove</button></> : <><div className="upload-icon"><UploadCloud size={26} /></div><strong>Drop a file here, or <label htmlFor="file-input">browse</label></strong><span>Images, video, audio, and documents</span></>}</div>{file?.type.startsWith('audio/') && <button className="button secondary transcript-button" onClick={() => void transcribe()} disabled={transcribing}>{transcribing ? 'Transcribing...' : 'Transcribe with Whisper'}</button>}<label className="field-label" htmlFor="context">Add context <span>Optional</span></label><textarea id="context" value={context} onChange={(event) => setContext(event.target.value)} placeholder="What should SATYA pay attention to?" rows={4} />{transcript && <div className="transcript"><strong>Whisper transcript</strong><p>{transcript}</p></div>}<div className="upload-footer"><span className="muted">Files are sent only when you start an analysis.</span><button className="button primary" onClick={() => void submit()} disabled={!file || busy}>{busy ? 'Analyzing...' : 'Start analysis'} <ArrowRight size={15} /></button></div>{error && <p className="error">{error}</p>}</div></div>
}

function Result() { const { id } = useParams(); const location = useLocation(); const [result, setResult] = useState<Analysis | undefined>((location.state as { result?: Analysis } | null)?.result); const [error, setError] = useState(''); useEffect(() => { if (!result && id) getAnalysis(id).then(setResult).catch((err) => setError(err.message)) }, [id, result]); if (error) return <div className="page"><p className="error">{error}</p></div>; if (!result) return <div className="loading-screen">Loading result...</div>; return <div className="page narrow"><Link to="/history" className="back-link"><ArrowLeft size={15} /> Back to history</Link><div className="result-heading"><div><p className="kicker">Analysis result</p><h2>{result.filename}</h2><p className="muted">{new Date(result.createdAt).toLocaleString()}</p></div><span className={`status ${result.verdict}`}><i />{verdictLabel[result.verdict]}</span></div><section className="card details-card"><span className="section-label">Summary</span><p className="result-summary">{result.summary}</p><strong>Confidence: {Math.round(result.confidence * 100)}%</strong></section><section className="card evidence-card"><span className="section-label">Evidence</span>{result.evidence.length ? result.evidence.map((item) => <div className="evidence-row" key={item.title}><strong>{item.title}</strong><p>{item.detail}</p></div>) : <p className="muted">No evidence was returned.</p>}</section></div> }

function History() { const [items, setItems] = useState<Analysis[]>([]); const [query, setQuery] = useState(''); const [error, setError] = useState(''); useEffect(() => { listAnalyses().then(setItems).catch((err) => setError(err.message)) }, []); const filtered = items.filter((item) => item.filename.toLowerCase().includes(query.toLowerCase())); return <div className="page"><div className="page-intro"><p className="kicker">Your records</p><h2>Analysis history</h2><p className="muted">Review analyses saved to your personal workspace.</p></div><div className="history-toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search files..." /></div><section className="card history-card"><AnalysisTable items={filtered} /><p className="error">{error}</p></section></div> }
function AnalysisTable({ items }: { items: Analysis[] }) { if (!items.length) return <div className="empty-state"><HistoryIcon size={24} /><p>No analyses yet.</p><Link to="/analyze" className="text-link">Create your first analysis <ArrowRight size={15} /></Link></div>; return <div className="table-wrap"><table><thead><tr><th>File</th><th>Result</th><th>Confidence</th><th>Date</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><Link to={`/results/${item.id}`} className="file-cell"><span className="mini-file"><FileCheck2 size={15} /></span><strong>{item.filename}</strong></Link></td><td><span className={`status ${item.verdict}`}><i />{verdictLabel[item.verdict]}</span></td><td>{Math.round(item.confidence * 100)}%</td><td className="date-cell">{new Date(item.createdAt).toLocaleDateString()}</td><td><Link to={`/results/${item.id}`} className="row-arrow"><ArrowRight size={16} /></Link></td></tr>)}</tbody></table></div> }

function Login() { const { session, configured, signIn, signUp } = useAuth(); const navigate = useNavigate(); const [signup, setSignup] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); if (session) return <Navigate to="/" replace />; async function submit() { setError(''); setMessage(''); try { if (signup) { await signUp(email, password); setMessage('Account created. Check your email if confirmation is enabled, then sign in.') } else { await signIn(email, password); navigate('/') } } catch (err) { setError(err instanceof TypeError ? 'Unable to reach Supabase. Check VITE_SUPABASE_URL in frontend/.env and restart the Vite server.' : err instanceof Error ? err.message : 'Authentication failed') } } return <div className="auth-page"><div className="auth-card"><Link to="/" className="brand"><span className="brand-mark"><ShieldCheck size={19} /></span><span>SATYA</span></Link><h1>{signup ? 'Create your account' : 'Welcome back'}</h1><p className="muted">{signup ? 'Start your personal authenticity workspace.' : 'Sign in to continue to your workspace.'}</p>{!configured && <p className="error">Supabase is not configured. Replace the placeholder values in frontend/.env with your Supabase project URL and anon key, then restart the Vite server.</p>}<label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<input type="password" minLength={6} value={password} onChange={(event) => setPassword(event.target.value)} /></label><button className="button primary auth-submit" onClick={() => void submit()} disabled={!configured}>{signup ? 'Sign up' : 'Sign in'}</button>{message && <p className="success">{message}</p>}{error && <p className="error">{error}</p>}<button className="text-button" onClick={() => setSignup((value) => !value)}>{signup ? 'Already have an account? Sign in' : 'Need an account? Sign up'}</button></div></div> }

function Settings() { const { session, signOut, deleteAccount } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); async function remove() { if (!window.confirm('Delete your account and all saved analyses? This cannot be undone.')) return; try { await deleteAccount(); navigate('/login') } catch (err) { setError(err instanceof Error ? err.message : 'Unable to delete account') } } return <div className="page narrow"><div className="page-intro"><p className="kicker">Workspace</p><h2>Settings</h2><p className="muted">Manage your account and preferences.</p></div><section className="card settings-section"><h3>Account</h3><p className="muted">{session?.user.email}</p><button className="button secondary" onClick={() => void signOut().then(() => navigate('/login')).catch((err) => setError(err.message))}><LogOut size={16} /> Sign out</button></section><section className="card settings-section danger-zone"><h3>Delete account</h3><p className="muted">Permanently delete your account and all analyses saved to it.</p><button className="button danger" onClick={() => void remove()}>Delete account</button>{error && <p className="error">{error}</p>}</section></div> }

function Help() { return <div className="help-page"><div className="auth-card"><Link to="/" className="brand"><span className="brand-mark"><ShieldCheck size={19} /></span><span>SATYA</span></Link><h1>Help & docs</h1><p className="muted">SATYA analyzes uploaded media using the configured backend pipeline. Results are probabilistic and should be reviewed before making high-impact decisions.</p><h3>Getting started</h3><p className="muted">Create an account, sign in, choose Analyze content, upload a file, and review the evidence returned by the API. Audio files can be transcribed through the Whisper button when a backend Whisper key is configured.</p><Link to="/login" className="text-link">Back to sign in <ArrowRight size={15} /></Link></div></div> }
